import {setToken} from './admin';
const issuer=import.meta.env.VITE_OIDC_ISSUER||'http://localhost:18085/realms/ai-hub-r2';
const client=import.meta.env.VITE_OIDC_CLIENT_ID||'ai-hub-admin';
let logoutEndpoint='';
let refreshTimer:number|undefined;
const b64=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=/g,'');
async function discovery(){const r=await fetch(`${issuer}/.well-known/openid-configuration`);if(!r.ok)throw new Error('Identidade indisponível. Tente novamente.');const d=await r.json();if(d.issuer!==issuer)throw new Error('Emissor de identidade inválido');logoutEndpoint=d.end_session_endpoint;return d;}
export async function login(){const d=await discovery();const verifier=b64(crypto.getRandomValues(new Uint8Array(32)));const state=b64(crypto.getRandomValues(new Uint8Array(24)));const challenge=b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))));sessionStorage.setItem('atlas.pkce',JSON.stringify({state,verifier,path:location.pathname+location.search,created:Date.now()}));const q=new URLSearchParams({client_id:client,response_type:'code',redirect_uri:location.origin+'/auth/callback',scope:'openid profile',state,code_challenge:challenge,code_challenge_method:'S256'});location.assign(`${d.authorization_endpoint}?${q}`);}
export async function acceptSession():Promise<boolean>{
 if(location.pathname!='/auth/callback')return false;
 const stored=sessionStorage.getItem('atlas.pkce');sessionStorage.removeItem('atlas.pkce');const p=new URLSearchParams(location.search);if(!stored)throw new Error('Sessão de entrada ausente; inicie novamente.');const flow=JSON.parse(stored);if(flow.state!==p.get('state')||Date.now()-flow.created>300000||!p.get('code'))throw new Error('Resposta de identidade inválida ou expirada');const d=await discovery();const response=await fetch(d.token_endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'authorization_code',client_id:client,code:p.get('code')!,code_verifier:flow.verifier,redirect_uri:location.origin+'/auth/callback'})});if(!response.ok)throw new Error('Não foi possível confirmar a sessão');const data=await response.json();setToken(data.access_token);scheduleRefresh(d.token_endpoint,data.refresh_token,data.expires_in);history.replaceState({},'',flow.path.startsWith('/')&&!flow.path.startsWith('//')?flow.path:'/services');return true;
}
function scheduleRefresh(endpoint:string,refresh:string,expires:number){if(refreshTimer)clearTimeout(refreshTimer);refreshTimer=window.setTimeout(async()=>{try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:refresh,client_id:client})});if(!r.ok)throw new Error('Sessão expirada');const d=await r.json();setToken(d.access_token);scheduleRefresh(endpoint,d.refresh_token,d.expires_in)}catch{setToken('');window.dispatchEvent(new Event('session-expired'))}},Math.max(5,expires-30)*1000)}
export async function logout(){if(refreshTimer)clearTimeout(refreshTimer);setToken('');sessionStorage.removeItem('atlas.pkce');history.replaceState({},'','/services');if(!logoutEndpoint){try{await discovery()}catch{return}};if(logoutEndpoint)location.assign(`${logoutEndpoint}?${new URLSearchParams({client_id:client,post_logout_redirect_uri:location.origin+'/services'})}`)}
