import {FormEvent,useEffect,useRef,useState} from 'react';
import {APIError,api,command,Page,Principal,Resource,resourceURL,Validation} from '../api/admin';
import {navigate} from '../navigation';

type Field={key:string;label:string;type?:'number'|'json'|'select'|'checkbox'|'datetime-local';options?:string[];reference?:string;hint?:string;multiple?:boolean};
const temporal:Field[]=[{key:'modes',label:'Modalidades',type:'select',multiple:true,options:['ASYNC','SYNC','AUTO']},{key:'provider_mode',label:'Modalidade do provedor',type:'select',options:['sync','async_poll','async_callback']},{key:'auto_wait_seconds',label:'Espera AUTO (segundos)',type:'number',hint:'Espera pelo final na conexão, limitada pelo SLA.'},{key:'client_sla_seconds',label:'SLA do cliente (segundos)',type:'number'},{key:'provider_sla_seconds',label:'SLA do provedor (segundos)',type:'number'},{key:'provider_sla_policy',label:'Política do SLA do provedor',type:'select',options:['MONITOR_ONLY','REJECT_LATE'],hint:'MONITOR_ONLY registra a violação; REJECT_LATE não finaliza sucesso após o prazo do provedor.'},{key:'retry_ttl_seconds',label:'TTL de reprocessamento (segundos)',type:'number',hint:'Contado a partir do aceite. O menor prazo entre TTL e SLA prevalece, sem renovação.'},{key:'finalization_reserve_seconds',label:'Reserva para finalização (segundos)',type:'number'},{key:'sync_http_budget_seconds',label:'Orçamento HTTP síncrono (segundos)',type:'number'}];
const schemas:Field[]=[{key:'input_schema',label:'Schema JSON de entrada',type:'json'},{key:'output_schema',label:'Schema JSON de saída',type:'json'}];
const definitions:Record<string,Field[]>={
 clients:[{key:'environment',label:'Ambiente',type:'select',options:['local','dev','hom','ppd','prd']},{key:'cell_id',label:'Célula de destino'},{key:'capacity_units',label:'Capacidade requerida',type:'number'},{key:'isolation_class',label:'Isolamento',type:'select',options:['SHARED','DEDICATED']}],
 applications:[{key:'environment',label:'Ambiente',type:'select',options:['local','dev','hom','ppd','prd']},{key:'scopes',label:'Permissões solicitadas',type:'json',hint:'Concessão de identidade é aplicada pelo administrador de identidade.'}],
 services:[...temporal,...schemas,{key:'data_class',label:'Classificação de dados',type:'select',options:['SYNTHETIC','PUBLIC','INTERNAL','PERSONAL','SENSITIVE']},{key:'adapter_id',label:'Adapter qualificado'},{key:'adapter_contract',label:'Contrato do adapter REST (JSON)',type:'json',hint:'Para rest-json-v1, use somente paths relativos: {"submit_path":"/analise","status_path":"/consulta/{id}"}. O host permanece na conta externa.'},{key:'qualification_id',label:'Evidência de homologação'}],
 products:[{key:'max_parallel',label:'Máximo de passos simultâneos',type:'number'},{key:'allow_partial',label:'Permitir resultado parcial',type:'checkbox'},{key:'consolidation',label:'Consolidação',type:'select',options:['ALL_REQUIRED']},{key:'failure_policy',label:'Em falha obrigatória',type:'select',options:['STOP','COMPENSATE']}],
 offers:[{key:'application_id',label:'Aplicação',reference:'applications'},{key:'target_kind',label:'Tipo de oferta',type:'select',options:['services','products']},{key:'target_id',label:'Serviço ou produto',reference:'target'},{key:'technical_profile_id',label:'Perfil técnico',reference:'technical-profiles'},{key:'purchase_contract_id',label:'Contrato de compra',reference:'contracts'},{key:'sale_contract_id',label:'Contrato de venda',reference:'contracts'},...temporal,{key:'valid_from',label:'Início da vigência',type:'datetime-local'},{key:'valid_until',label:'Fim da vigência',type:'datetime-local'}],
 'technical-profiles':[...temporal,...schemas,{key:'media_type',label:'Formato da resposta',type:'select',options:['application/json']},{key:'input_mapping',label:'Campos de entrada: destino → origem',type:'json',hint:'Somente nomes de campos. Sem código, rede ou valores inventados.'},{key:'output_mapping',label:'Campos de saída: destino → origem',type:'json'}],
 providers:[{key:'environment',label:'Ambiente externo'}],
 'provider-accounts':[{key:'provider_id',label:'Provedor',reference:'providers'},{key:'environment',label:'Ambiente externo',hint:'Ambiente do parceiro, por exemplo sandbox.'},{key:'base_url',label:'URL base autorizada'},{key:'provider_mode',label:'Modalidade do provedor',type:'select',options:['sync','async_poll','async_callback']},{key:'auth_type',label:'Autenticação',type:'select',options:['NONE','BASIC','API_KEY','OAUTH_CLIENT_CREDENTIALS','MTLS_OAUTH']},{key:'api_key_header',label:'Header da API Key',hint:'Somente o nome do header; o valor fica no cofre.'},{key:'auth_username',label:'Usuário Basic'},{key:'oauth_token_url',label:'URL do token OAuth'},{key:'oauth_client_id',label:'Client ID OAuth'},{key:'mtls_certificate_ref',label:'Referência do certificado mTLS',hint:'Referência do cofre; nunca cole material privado.'},{key:'capacity_domain',label:'Domínio de capacidade'}],
 'credential-bindings':[{key:'provider_account_id',label:'Conta externa',reference:'provider-accounts'},{key:'credential_mode',label:'Titular da credencial',type:'select',options:['TENANT_DEDICATED','SHARED_HUB']},{key:'secret_ref',label:'Referência autorizada do segredo',hint:'Informe somente o identificador do cofre; nunca cole um segredo.'},{key:'secret_version',label:'Versão do segredo'},{key:'settlement_party',label:'Responsável pelo pagamento',type:'select',options:['HUB','CLIENT_DIRECT']},{key:'valid_from',label:'Início de validade',type:'datetime-local'},{key:'valid_until',label:'Fim de validade',type:'datetime-local'}],
 contracts:[{key:'contract_kind',label:'Natureza',type:'select',options:['PURCHASE','SALE']},{key:'currency',label:'Moeda',type:'select',options:['BRL','USD','EUR']},{key:'unit_price',label:'Preço decimal',hint:'Valor exato transmitido como texto, por exemplo 1.0000.'},{key:'settlement_party',label:'Responsável pelo pagamento',type:'select',options:['HUB','CLIENT_DIRECT']},{key:'meter',label:'Marco de cobrança',type:'select',options:['SUCCESS','SUBMISSION','PARTIAL_SUCCESS','STATUS','FETCH']},{key:'unit_scope',label:'Unidade econômica',type:'select',options:['PROTOCOL','STEP','OPERATION','ATTEMPT']},{key:'strict_balance',label:'Exigir reserva antes do envio',type:'checkbox'},{key:'reservation_amount',label:'Valor máximo da reserva',hint:'Obrigatório quando houver saldo estrito; valor decimal explícito.'},{key:'pricing_rules',label:'Regras de plano publicadas',type:'json',hint:'Opcional para múltiplos marcos e planos; regras substituem o preço unitário simples.'},{key:'valid_from',label:'Início de vigência',type:'datetime-local'},{key:'valid_until',label:'Fim de vigência',type:'datetime-local'}],
 policies:temporal,
};
const titles:Record<string,string>={clients:'Clientes',applications:'Aplicações',services:'Serviços',products:'Produtos',offers:'Ofertas','technical-profiles':'Perfis técnicos',providers:'Provedores','provider-accounts':'Contas externas','credential-bindings':'Vínculos de credencial',contracts:'Contratos comerciais',policies:'Prazos e políticas'};
const blankData=(kind:string):Record<string,unknown>=>({modes:['ASYNC'],provider_mode:'sync',client_sla_seconds:30,auto_wait_seconds:5,provider_sla_seconds:10,provider_sla_policy:'MONITOR_ONLY',retry_ttl_seconds:10,finalization_reserve_seconds:2,sync_http_budget_seconds:15,input_schema:{type:'object',properties:{marker:{type:'string'}},required:['marker']},output_schema:{type:'object',properties:{marker:{type:'string'}},required:['marker']},data_class:'SYNTHETIC',media_type:'application/json',input_mapping:{},output_mapping:{},steps:[],routes:[],max_parallel:2,consolidation:'ALL_REQUIRED',failure_policy:'STOP',allow_partial:false,environment:'local',target_kind:'services',credential_mode:'TENANT_DEDICATED',settlement_party:'HUB',currency:'BRL',unit_price:'1.0000',contract_kind:'SALE',meter:'SUCCESS',unit_scope:'PROTOCOL',strict_balance:false,pricing_rules:[],...(kind==='applications'?{scopes:[]}:{} )});
function localDateTime(value:unknown){const date=new Date(String(value||''));if(Number.isNaN(date.getTime()))return '';const pad=(part:number)=>String(part).padStart(2,'0');return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`}
async function loadLookup(kind:string,tenant:string,signal:AbortSignal){const items:Resource[]=[];let cursor='';for(let page=0;page<10;page++){const params=new URLSearchParams({tenant_id:tenant,limit:'100'});if(cursor)params.set('cursor',cursor);const result=await api<Page<Resource>>(`/admin/v1/${kind}?${params}`,{signal});items.push(...result.items);if(!result.next_cursor)return items;cursor=result.next_cursor}throw new Error(`catálogo de referência ${kind} excede o limite seguro de 1000 registros`)}
export default function CatalogPage({kind,tenant,principal,route}:{kind:string;tenant:string;principal:Principal;route:string}){
 const [items,setItems]=useState<Resource[]>([]);const [next,setNext]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');const [lookupError,setLookupError]=useState('');const [message,setMessage]=useState('');const [draft,setDraft]=useState<Resource|null>(null);const [original,setOriginal]=useState<Resource|null>(null);const [validation,setValidation]=useState<Validation|null>(null);const [reason,setReason]=useState('');const [lookups,setLookups]=useState<Record<string,Resource[]>>({});const [conflict,setConflict]=useState<Resource|null>(null);const [revision,setRevision]=useState(0);const [jsonErrors,setJSONErrors]=useState<Record<string,string>>({});const alertRef=useRef<HTMLDivElement>(null);
 const query=new URLSearchParams(route.split('?')[1]);const search=query.get('q')||'';const state=query.get('state')||'';const cursor=query.get('cursor')||'';const parts=route.split('?')[0].split('/').filter(Boolean);const detail=parts.length>=3;const creating=parts[1]==='new';
 const permission=kind==='contracts'?'finance:write':['providers','provider-accounts','credential-bindings'].includes(kind)?'integrations:write':'catalog:write';const canWrite=principal.scopes.includes(permission);const canPublish=principal.scopes.includes(permission==='catalog:write'?'catalog:publish':permission);
 const scope=`tenant_id=${encodeURIComponent(tenant)}`;
 const dirty=!!draft&&(creating||!original||draft.name!==original.name||JSON.stringify(draft.data)!==JSON.stringify(original.data));
 useEffect(()=>{const abort=new AbortController();setLoading(true);setError('');setMessage('');setValidation(null);setConflict(null);setJSONErrors({});
 if(creating){setDraft({kind,id:'',version:1,tenant_id:tenant,name:'',state:'DRAFT',revision:0,data:blankData(kind),content_hash:'',author:'',updated_at:''});setOriginal(null);setLoading(false);return()=>abort.abort()}
 if(detail){api<Resource>(`/admin/v1/${kind}/${encodeURIComponent(parts[1])}/${parts[2]}?${scope}`,{signal:abort.signal}).then(r=>{setDraft(r);setOriginal(r)}).catch(e=>{if(!abort.signal.aborted)setError(String(e))}).finally(()=>{if(!abort.signal.aborted)setLoading(false)})}
 else{setDraft(null);const params=new URLSearchParams({tenant_id:tenant,q:search,state,limit:'25',cursor});api<Page<Resource>>(`/admin/v1/${kind}?${params}`,{signal:abort.signal}).then(p=>{setItems(p.items);setNext(p.next_cursor)}).catch(e=>{if(!abort.signal.aborted)setError(`Consulta indisponível; os dados anteriores podem estar desatualizados. ${e}`)}).finally(()=>{if(!abort.signal.aborted)setLoading(false)})}return()=>abort.abort()
 },[kind,tenant,route,revision]);
 useEffect(()=>{if(!draft)return;const abort=new AbortController();const refs=Array.from(new Set((definitions[kind]||[]).filter(f=>f.reference).map(f=>f.reference==='target'?String(draft.data.target_kind||'services'):f.reference!)));if(kind==='products')refs.push('services');if(kind==='offers')refs.push('provider-accounts','credential-bindings');setLookupError('');void Promise.all(refs.map(async ref=>[ref,await loadLookup(ref,tenant,abort.signal)] as const)).then(entries=>{if(!abort.signal.aborted)setLookups(Object.fromEntries(entries))}).catch(reason=>{if(!abort.signal.aborted){setLookups({});setLookupError(`Referências do catálogo indisponíveis; a edição não será tratada como lista vazia. ${String(reason)}`)}});return()=>abort.abort()},[!!draft,kind,tenant,draft?.data.target_kind]);
 useEffect(()=>{if(!dirty)return;const warn=(event:BeforeUnloadEvent)=>{event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
 function setData(key:string,value:unknown){setDraft(d=>d?{...d,data:{...d.data,[key]:value}}:null);setValidation(null)}
 function fail(e:unknown){if(e instanceof APIError){if(e.status===412&&e.body.current)setConflict(e.body.current as Resource);if(e.body.field_errors)setValidation(e.body as unknown as Validation)}setError(String(e));setTimeout(()=>alertRef.current?.focus(),0)}
 async function save(e:FormEvent){e.preventDefault();if(!draft||loading)return;setError('');setMessage('');if(Object.keys(jsonErrors).length){setError('Corrija os campos JSON indicados.');alertRef.current?.focus();return};setLoading(true);try{const createPayload={kind:draft.kind,id:draft.id,version:draft.version,tenant_id:draft.tenant_id,name:draft.name,data:draft.data};const saved=creating?await command<Resource>(`/admin/v1/${kind}?${scope}`,createPayload):await api<Resource>(`${resourceURL(draft)}?${scope}`,{method:'PATCH',headers:{'If-Match':`"${draft.revision}"`},body:JSON.stringify({name:draft.name,data:draft.data})});setDraft(saved);setOriginal(saved);setMessage('Rascunho salvo no servidor. A publicação é uma ação separada.');if(creating)navigate(`/${kind}/${saved.id}/${saved.version}`)}catch(e){fail(e)}finally{setLoading(false)}}
 async function validate(){if(!draft)return;setLoading(true);setError('');try{const v=await command<Validation>(`${resourceURL(draft)}/simulate?${scope}`,{});setValidation(v);if(!v.valid)setTimeout(()=>alertRef.current?.focus(),0)}catch(e){fail(e)}finally{setLoading(false)}}
 async function action(action:'publish'|'suspend'){if(!draft)return;setLoading(true);setError('');try{const saved=await command<Resource>(`${resourceURL(draft)}/${action}?${scope}`,{reason,content_hash:validation?.content_hash},draft.revision);setDraft(saved);setOriginal(saved);setMessage(action==='publish'?`Versão ${saved.version} publicada. Conteúdo imutável.`:'Novas admissões suspensas. Histórico preservado.')}catch(e){fail(e)}finally{setLoading(false)}}
 const disabled=loading||!canWrite||draft?.state!=='DRAFT';
 return <section><div className="page-title"><h2>{titles[kind]}</h2>{!draft&&canWrite&&<a href={`/${kind}/new`} onClick={e=>{e.preventDefault();navigate(`/${kind}/new`)}}>Criar rascunho</a>}{draft&&<a href={`/${kind}`} onClick={e=>{e.preventDefault();navigate(`/${kind}`)}}>Voltar à lista</a>}</div>
 {loading&&<p role="status">Carregando…</p>}<div ref={alertRef} tabIndex={-1} role="alert" aria-live="assertive">{error&&<p className="error">{error}</p>}{lookupError&&<p className="error">{lookupError}</p>}{validation&&!validation.valid&&<div><p>Publicação bloqueada:</p><ul>{Object.entries(validation.field_errors).map(([field,msg])=><li key={field}><a href={`#field-${field}`}>{field}: {msg}</a></li>)}</ul></div>}</div>{message&&<p role="status" aria-live="polite" className="success">{message}</p>}
 {conflict&&<div className="conflict"><h3>Outra revisão foi salva</h3><p>Sua entrada foi preservada. Compare antes de recarregar a versão do servidor.</p><div className="diff"><pre aria-label="Sua edição">{JSON.stringify(draft?.data,null,2)}</pre><pre aria-label="Versão atual">{JSON.stringify(conflict.data,null,2)}</pre></div><button onClick={()=>{setDraft(conflict);setOriginal(conflict);setConflict(null);setError('')}}>Usar revisão do servidor</button></div>}
 {!draft&&!loading&&<><form className="filters" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);navigate(`/${kind}?${new URLSearchParams({q:String(f.get('q')||''),state:String(f.get('state')||'')})}`)}}><label>Buscar por nome<input name="q" defaultValue={search} maxLength={128}/></label><label>Estado<select name="state" defaultValue={state}><option value="">Todos</option>{['DRAFT','PUBLISHED','SUSPENDED'].map(s=><option key={s}>{s}</option>)}</select></label><button>Buscar</button><button type="button" onClick={()=>setRevision(x=>x+1)}>Atualizar</button></form><div className="table-scroll" tabIndex={0} aria-label="Lista navegável"><table><thead><tr><th>Nome</th><th>Versão</th><th>Estado</th><th>Atualizado</th><th>Ação</th></tr></thead><tbody>{items.map(r=><tr key={`${r.id}/${r.version}`}><td>{r.name}</td><td>{r.version}</td><td>{r.state}</td><td>{new Date(r.updated_at).toLocaleString('pt-BR')}</td><td><a href={`/${kind}/${r.id}/${r.version}`} onClick={e=>{e.preventDefault();navigate(`/${kind}/${r.id}/${r.version}`)}}>Abrir {r.name}</a></td></tr>)}</tbody></table></div>{!items.length&&!error&&<p>Nenhum registro encontrado neste filtro.</p>}{next&&<button onClick={()=>navigate(`/${kind}?${new URLSearchParams({q:search,state,cursor:next})}`)}>Próxima página</button>}</>}
 {draft&&<><p>Cliente: {draft.tenant_id||'Catálogo compartilhado'} · {draft.state} · Revisão {draft.revision}</p><form onSubmit={save} className="resource-form"><fieldset disabled={disabled}><legend>Identificação</legend><label>Nome<input id="field-name" required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Código estável<input required disabled={!creating} value={draft.id} onChange={e=>setDraft({...draft,id:e.target.value})} pattern="[^/\\]+" maxLength={128}/></label><label>Versão<input type="number" min={1} required disabled={!creating} value={draft.version} onChange={e=>setDraft({...draft,version:Number(e.target.value)})}/></label></fieldset>
 <fieldset disabled={disabled}><legend>Configuração da versão</legend><div className="form-grid">{(definitions[kind]||[]).map(field=>{const value=draft.data[field.key];const ref=field.reference==='target'?String(draft.data.target_kind||'services'):field.reference;return <label key={field.key} className={field.type==='json'?'wide':''} htmlFor={`field-${field.key}`}>{field.label}
 {ref?<select id={`field-${field.key}`} value={String(value||'')+'@'+String(draft.data[field.key.replace(/_id$/,'_version')]||1)} onChange={e=>{const [id,version]=e.target.value.split('@');setDraft({...draft,data:{...draft.data,[field.key]:id,[field.key.replace(/_id$/,'_version')]:Number(version)}})}}><option value="@1">Selecione um registro</option>{(lookups[ref]||[]).map(r=><option key={`${r.id}@${r.version}`} value={`${r.id}@${r.version}`}>{r.name} · v{r.version} · {r.state}</option>)}</select>:field.type==='json'?<textarea id={`field-${field.key}`} rows={5} defaultValue={JSON.stringify(value??{},null,2)} key={`${draft.id}:${draft.revision}:${field.key}`} aria-invalid={!!jsonErrors[field.key]} aria-describedby={`hint-${field.key}`} onChange={e=>{try{setData(field.key,JSON.parse(e.target.value));setJSONErrors(prev=>{const next={...prev};delete next[field.key];return next})}catch{setJSONErrors(prev=>({...prev,[field.key]:'JSON inválido; entrada preservada'}))}}}/>:field.type==='select'?<select id={`field-${field.key}`} multiple={field.multiple} value={field.multiple&&Array.isArray(value)?value.map(String):String(value||'')} onChange={e=>setData(field.key,field.multiple?Array.from(e.target.selectedOptions).map(option=>option.value):e.target.value)}><option value="">Selecione</option>{field.options?.map(o=><option key={o}>{o}</option>)}</select>:field.type==='checkbox'?<input id={`field-${field.key}`} type="checkbox" checked={!!value} onChange={e=>setData(field.key,e.target.checked)}/>:<input id={`field-${field.key}`} type={field.type||'text'} min={0} value={field.type==='datetime-local'?localDateTime(value):String(value??'')} onChange={e=>setData(field.key,field.type==='number'?Number(e.target.value):field.type==='datetime-local'?(e.target.value?new Date(e.target.value).toISOString():null):e.target.value)}/>}
 <small id={`hint-${field.key}`}>{jsonErrors[field.key]||field.hint}</small></label>})}</div></fieldset>
 {kind==='products'&&<StepsEditor draft={draft} setData={setData} services={lookups.services||[]} disabled={disabled}/>}{kind==='offers'&&<RoutesEditor draft={draft} setData={setData} accounts={lookups['provider-accounts']||[]} bindings={lookups['credential-bindings']||[]} disabled={disabled}/>}
 {canWrite&&draft.state==='DRAFT'&&<div className="form-actions"><button type="submit" disabled={loading}>Salvar rascunho</button>{!creating&&dirty&&<button type="button" disabled={loading} onClick={()=>{if(original)setDraft({...original,data:{...original.data}})}}>Restaurar última versão salva</button>}</div>}</form>
 {!creating&&<div className="publication"><h3>Validação e publicação</h3><p>Uma versão publicada preserva contratos já aceitos. Suspender impede novas admissões.</p><button disabled={loading} onClick={()=>void validate()}>Validar e simular sem efeitos externos</button>{validation&&<div role="status"><p>{validation.valid?'Validação aprovada':'Validação com pendências'} · Fixture: {validation.fixture}</p><p>TTL efetivo: {validation.effective_retry_seconds}s · Hash: <code>{validation.content_hash}</code></p>{validation.layers.length>0&&<><svg viewBox={`0 0 640 ${validation.layers.length*64}`} role="img" aria-label="Grafo por grupos de execução">{validation.layers.map((layer,i)=><g key={i}><text x={10} y={i*64+32}>{`Grupo ${i+1}: ${layer.join(' + ')}`}</text>{i>0&&<path d={`M 24 ${i*64-16} L 24 ${i*64+8}`} stroke="currentColor"/>}</g>)}</svg><ol>{validation.layers.map((layer,i)=><li key={i}>Após o grupo anterior: {layer.join(', ')}</li>)}</ol></>}</div>}
 <details><summary>Conteúdo persistido desta revisão</summary><pre>{JSON.stringify(original?.data,null,2)}</pre></details><label>Motivo da ação<input minLength={8} value={reason} onChange={e=>setReason(e.target.value)}/></label>{draft.state==='DRAFT'&&canPublish&&<button disabled={loading||!validation?.valid||reason.trim().length<8||JSON.stringify(draft.data)!==JSON.stringify(original?.data)} onClick={()=>void action('publish')}>Publicar versão {draft.version}</button>}{draft.state==='PUBLISHED'&&canPublish&&<button disabled={loading||reason.trim().length<8} onClick={()=>void action('suspend')}>Suspender novas admissões</button>}{draft.state!=='DRAFT'&&canWrite&&<button onClick={()=>{navigate(`/${kind}/new`);setTimeout(()=>setDraft({...draft,version:draft.version+1,state:'DRAFT',revision:0}),0)}}>Criar próxima versão</button>}</div>}</>}
 </section>
}
function StepsEditor({draft,setData,services,disabled}:{draft:Resource;setData:(k:string,v:unknown)=>void;services:Resource[];disabled:boolean}){
 const steps=(draft.data.steps||[]) as Record<string,unknown>[];
 const [mappingText,setMappingText]=useState<Record<number,string>>({});
 const [mappingErrors,setMappingErrors]=useState<Record<number,string>>({});
 useEffect(()=>{setMappingText({});setMappingErrors({})},[draft.id,draft.revision]);
 const update=(i:number,k:string,v:unknown)=>setData('steps',steps.map((s,j)=>i===j?{...s,[k]:v}:s));
 function updateMapping(i:number,raw:string){
  setMappingText(previous=>({...previous,[i]:raw}));
  try{
   const parsed=JSON.parse(raw);
   if(parsed===null||Array.isArray(parsed)||typeof parsed!=='object'||Object.entries(parsed).some(([key,value])=>!key.trim()||typeof value!=='string'||!value.trim()))throw new Error('objeto de campos esperado');
   update(i,'input_mapping',parsed);
   setMappingErrors(previous=>{const next={...previous};delete next[i];return next});
  }catch{setMappingErrors(previous=>({...previous,[i]:'JSON inválido; use um objeto destino → etapa.campo.'}))}
 }
 return <fieldset disabled={disabled}><legend>Passos do produto</legend>{steps.map((step,i)=>{const mapping=step.input_mapping&&typeof step.input_mapping==='object'&&!Array.isArray(step.input_mapping)?step.input_mapping:{};return <div className="step" key={i}><h4>Passo {i+1}</h4><label>Nome do passo<input value={String(step.id||'')} onChange={e=>update(i,'id',e.target.value)}/></label><label>Serviço<select value={`${step.service_id||''}@${step.service_version||1}`} onChange={e=>{const [id,version]=e.target.value.split('@');setData('steps',steps.map((s,j)=>i===j?{...s,service_id:id,service_version:Number(version)}:s))}}><option value="@1">Selecione</option>{services.map(s=><option key={`${s.id}/${s.version}`} value={`${s.id}@${s.version}`}>{s.name} · v{s.version}</option>)}</select></label><label>Depende dos passos (separados por vírgula)<input value={(step.depends_on as string[]||[]).join(',')} onChange={e=>update(i,'depends_on',e.target.value.split(',').map(s=>s.trim()).filter(Boolean))}/></label><label className="wide" htmlFor={`step-${i}-input-mapping`}>Mapeamento de entrada <textarea id={`step-${i}-input-mapping`} rows={4} value={mappingText[i]??JSON.stringify(mapping,null,2)} aria-invalid={!!mappingErrors[i]} aria-describedby={`step-${i}-input-mapping-hint`} onChange={e=>updateMapping(i,e.target.value)}/><small id={`step-${i}-input-mapping-hint`}>{mappingErrors[i]||'Objeto JSON: campo_destino → passo_anterior.campo_resultado. Para etapas iniciais, mantenha {}.'}</small></label><label><input type="checkbox" checked={!!step.required} onChange={e=>update(i,'required',e.target.checked)}/>Obrigatório</label><label>Serviço de compensação<select value={`${step.compensation_service_id||''}@${step.compensation_service_version||1}`} onChange={e=>{const [id,version]=e.target.value.split('@');setData('steps',steps.map((s,j)=>i===j?{...s,compensation_service_id:id,compensation_service_version:id?Number(version):undefined}:s))}}><option value="@1">Sem compensação</option>{services.map(s=><option key={`${s.id}/${s.version}`} value={`${s.id}@${s.version}`}>{s.name} · v{s.version}</option>)}</select></label><button type="button" onClick={()=>setData('steps',steps.filter((_,j)=>i!==j))}>Remover passo {i+1}</button></div>})}<button type="button" disabled={steps.length>=20} onClick={()=>setData('steps',[...steps,{id:`passo${steps.length+1}`,service_id:'',service_version:1,depends_on:[],required:true,input_mapping:{}}])}>Adicionar passo</button></fieldset>
}
function RoutesEditor({draft,setData,accounts,bindings,disabled}:{draft:Resource;setData:(k:string,v:unknown)=>void;accounts:Resource[];bindings:Resource[];disabled:boolean}){const routes=(draft.data.routes||[]) as Record<string,unknown>[];const update=(i:number,k:string,v:unknown)=>setData('routes',routes.map((s,j)=>i===j?{...s,[k]:v}:s));return <fieldset disabled={disabled}><legend>Rotas autorizadas</legend>{routes.map((route,i)=><div className="step" key={i}><label>Conta externa<select value={String(route.provider_account_id||'')} onChange={e=>{const selected=accounts.find(a=>a.id===e.target.value);setData('routes',routes.map((r,j)=>i===j?{...r,provider_account_id:e.target.value,provider_account_version:selected?.version}:r))}}><option value="">Selecione</option>{accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>Vínculo de credencial<select value={`${route.binding_id||''}@${route.binding_version||1}`} onChange={e=>{const [id,v]=e.target.value.split('@');setData('routes',routes.map((r,j)=>i===j?{...r,binding_id:id,binding_version:Number(v)}:r))}}><option value="@1">Selecione</option>{bindings.map(b=><option value={`${b.id}@${b.version}`} key={`${b.id}/${b.version}`}>{b.name} · v{b.version}</option>)}</select></label><label>Prioridade<input type="number" value={Number(route.priority||0)} onChange={e=>update(i,'priority',Number(e.target.value))}/></label><label>Homologação de equivalência<input value={String(route.equivalence_id||'')} onChange={e=>update(i,'equivalence_id',e.target.value)}/></label><label>Domínio de capacidade<input value={String(route.capacity_domain||'')} onChange={e=>update(i,'capacity_domain',e.target.value)}/></label><button type="button" onClick={()=>setData('routes',routes.filter((_,j)=>i!==j))}>Remover rota</button></div>)}<button type="button" disabled={routes.length>=5} onClick={()=>setData('routes',[...routes,{provider_account_id:'',binding_id:'',binding_version:1,priority:routes.length,capacity_domain:'',equivalence_id:''}])}>Adicionar rota</button></fieldset>}
