import {useEffect,useState} from 'react';
import {api,command,Page,Principal} from '../api/admin';
import {navigate,useRoute} from '../navigation';
type RecordData=Record<string,unknown>;
export default function OperationsPage({kind,tenant,principal}:{kind:string;tenant:string;principal:Principal}){const route=useRoute();const query=new URLSearchParams(route.split('?')[1]);const id=route.split('?')[0].split('/')[2];const [items,setItems]=useState<RecordData[]>([]);const [next,setNext]=useState('');const [detail,setDetail]=useState<RecordData|null>(null);const [timeline,setTimeline]=useState<RecordData[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [reason,setReason]=useState('');const [message,setMessage]=useState('');const [refresh,setRefresh]=useState(0);const scope=`tenant_id=${encodeURIComponent(tenant)}`;const title=kind==='protocols'?'Protocolos':kind==='deliveries'?'Entregas':'SLA bilateral';useEffect(()=>{const abort=new AbortController();setBusy(true);setError('');setDetail(null);setTimeline([]);const params=new URLSearchParams(query);params.set('tenant_id',tenant);params.set('limit','25');if(id){void api<RecordData>(`/admin/v1/${kind}/${encodeURIComponent(id)}?${scope}`,{signal:abort.signal}).then(setDetail).then(async()=>{if(kind==='protocols'){const t=await api<RecordData[]|{items:RecordData[]}>(`/admin/v1/protocols/${encodeURIComponent(id)}/timeline?${scope}`,{signal:abort.signal});setTimeline(Array.isArray(t)?t:t.items)}}).catch(e=>{if(!abort.signal.aborted)setError(String(e))}).finally(()=>{if(!abort.signal.aborted)setBusy(false)})}else{void api<Page<RecordData>|RecordData>(`/admin/v1/${kind}?${params}`,{signal:abort.signal}).then(p=>{setItems(Array.isArray(p.items)?p.items:[]);setNext(String(p.next_cursor||''));if(kind==='sla-reports')setDetail(p as RecordData)}).catch(e=>{if(!abort.signal.aborted)setError(`Consulta indisponível; dados anteriores desatualizados. ${e}`)}).finally(()=>{if(!abort.signal.aborted)setBusy(false)})}return()=>abort.abort()},[kind,tenant,route,refresh]);
 async function act(action:string){if(!id||busy)return;setBusy(true);setError('');try{const receipt=await command<RecordData>(`/admin/v1/${kind}/${encodeURIComponent(id)}/${action}?${scope}`,{reason});setMessage(`Ação registrada: ${JSON.stringify(receipt)}`);setRefresh(n=>n+1)}catch(e){setError(String(e))}finally{setBusy(false)}}
 return <section><h2>{title}</h2>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{busy&&<p role="status">Consultando autoridade do recurso…</p>}<form className="filters" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const protocol=String(f.get('protocol_id')||'');if(protocol)navigate(`/${kind}/${encodeURIComponent(protocol)}`);else navigate(`/${kind}?${new URLSearchParams({status:String(f.get('status')||''),from:String(f.get('from')||''),to:String(f.get('to')||'')})}`)}}><label>Identificador<input name="protocol_id" defaultValue={id||''}/></label><label>Estado<select name="status" defaultValue={query.get('status')||''}><option value="">Todos</option>{(kind==='deliveries'?['PENDING','DELIVERED','EXHAUSTED','SUSPENDED']:['ACCEPTED','RUNNING','WAITING_PROVIDER','SUCCEEDED','PARTIALLY_SUCCEEDED','FAILED','EXPIRED','UNKNOWN']).map(s=><option key={s}>{s}</option>)}</select></label><label>De<input name="from" type="date" defaultValue={query.get('from')||''}/></label><label>Até<input name="to" type="date" defaultValue={query.get('to')||''}/></label><button disabled={busy}>Consultar</button><button type="button" onClick={()=>setRefresh(n=>n+1)}>Atualizar</button></form>
 {!id&&kind!=='sla-reports'&&<><div className="table-scroll" tabIndex={0}><table><thead><tr><th>Identificador</th><th>Cliente</th><th>Estado</th><th>Data</th></tr></thead><tbody>{items.map((row,i)=>{const key=String(row.protocol_id||row.delivery_id||row.id||i);return <tr key={key}><td><a href={`/${kind}/${key}`} onClick={e=>{e.preventDefault();navigate(`/${kind}/${key}`)}}>{key}</a></td><td>{String(row.tenant_id||'')}</td><td>{String(row.status||row.state||'')}</td><td>{String(row.accepted_at||row.created_at||'')}</td></tr>})}</tbody></table></div>{!items.length&&!busy&&!error&&<p>Nenhum registro no filtro autorizado.</p>}{next&&<button onClick={()=>navigate(`/${kind}?${new URLSearchParams({...Object.fromEntries(query),cursor:next})}`)}>Próxima página</button>}</>}
 {detail&&<><h3>{kind==='sla-reports'?'Apuração e atualidade':'Detalhe persistido'}</h3><DefinitionList value={detail}/>{String(detail.status||detail.state)==='UNKNOWN'&&<p>A operação tem efeito externo incerto. Novo envio permanece bloqueado; use reconciliação autorizada.</p>}{timeline.length>0&&<><h3>Timeline</h3><ol className="timeline">{timeline.map((item,i)=><li key={i}><DefinitionList value={item}/></li>)}</ol></>}{id&&(kind==='deliveries'&&principal.scopes.includes('deliveries:write')||kind==='protocols'&&principal.scopes.includes('protocols:reconcile'))&&<div><label>Justificativa<input minLength={8} value={reason} onChange={e=>setReason(e.target.value)}/></label>{kind==='deliveries'&&String(detail.status||detail.state)==='EXHAUSTED'&&<button disabled={busy||reason.trim().length<8} onClick={()=>void act('redeliver')}>Reentregar mesmos bytes do webhook</button>}{kind==='protocols'&&<button disabled={busy||reason.trim().length<8} onClick={()=>void act('reconcile')}>Solicitar reconciliação</button>}</div>}</>}
 </section>
}
export function DefinitionList({value}:{value:RecordData}){return <dl className="definition-list">{Object.entries(value).map(([key,value])=><div key={key}><dt>{key.replace(/_/g,' ')}</dt><dd>{typeof value==='object'?<pre>{JSON.stringify(value,null,2)}</pre>:String(value??'Não informado')}</dd></div>)}</dl>}
