_format_version: '3.0'
services:
  - name: orbita
    url: http://orbita:8080
    routes:
      - name: protocols
        paths: [/v1/protocols]
        strip_path: false
  - name: cometa-callbacks
    url: http://cometa:8082
    routes:
      - name: callbacks
        paths: [/callbacks]
        strip_path: false
