server {
  listen 8080;
  root /usr/share/nginx/html;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy same-origin always;
  location / { try_files $uri $uri/ /index.html; }
  location /api/atlas/ { proxy_pass http://atlas:8081/; }
  location /api/orbita/ { proxy_pass http://orbita:8080/; }
  location /api/cometa/ { proxy_pass http://cometa:8082/; }
  location /api/pulsar/ { proxy_pass http://pulsar:8083/; }
  location /api/libra/ { proxy_pass http://libra:8084/; }
}
