import {createHmac} from 'node:crypto';
import {randomUUID} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {writeFile} from 'node:fs/promises';
const playwright=await import(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const chromium=playwright.chromium||playwright.default?.chromium;
if(!chromium) throw new Error('playwright-core sem export chromium');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_BIN||'/usr/bin/google-chrome'});
const page=await browser.newPage({viewport:{width:1365,height:900}});
const evidence=[];
const networkDiagnostics=[];
page.on('response',response=>{if(response.url().includes('/api/pulsar/admin/v1/deliveries/')||response.url().includes('/api/orbita/admin/v1/protocols/'))networkDiagnostics.push({url:response.url(),status:response.status()})});
const postgres=`${process.env.R2_COMPOSE_PROJECT||'ai_hub_r3qual'}-postgres-1`;
let seededDelivery='';
function sql(statement){return execFileSync('docker',['exec',postgres,'psql','-U','hub','-d','hub_core','-At','-v','ON_ERROR_STOP=1','-c',statement],{encoding:'utf8'}).trim()}
function sqlControl(statement){return execFileSync('docker',['exec',postgres,'psql','-U','hub','-d','hub_control','-At','-v','ON_ERROR_STOP=1','-c',statement],{encoding:'utf8'}).trim()}
let phase='inicialização';
const lastSuccessfulAuthCounter=new Map();
async function authenticate(username,expectedURL){
 const previousCounter=lastSuccessfulAuthCounter.get(username);
 if(previousCounter!==undefined){
  while(Math.floor(Date.now()/30000)<=previousCounter)await page.waitForTimeout(500);
 }
 if(!await page.locator('#otp').count()){
  await page.getByRole('button',{name:'Entrar',exact:true}).click();
  await page.locator('#username').fill(username);
  await page.locator('#password').fill('R2-fixture-password!');
  await page.locator('#kc-login').click();
  await page.locator('#otp').waitFor();
 }
 for(let attempt=0;attempt<3;attempt++){
  for(const skew of [0,-1,1]){
   if(!await page.locator('#otp').count())break;
   const counter=Buffer.alloc(8);counter.writeBigUInt64BE(BigInt(Math.floor(Date.now()/30000)+skew));
   const digest=createHmac('sha1',Buffer.from('AI-HUB-R2-MFA-KEY-01')).update(counter).digest();
   const offset=digest[digest.length-1]&15;
   const otp=((digest.readUInt32BE(offset)&0x7fffffff)%1000000).toString().padStart(6,'0');
   await page.locator('#otp').fill(otp);await page.locator('#kc-login').click();
   try{await page.waitForURL(expectedURL,{timeout:1500});lastSuccessfulAuthCounter.set(username,Math.floor(Date.now()/30000));return}catch{}
  }
  await page.waitForTimeout(250);
 }
 throw new Error('OIDC OTP não foi aceito após janela de relógio e três ciclos');
}
try {
 phase='autenticação inicial';
 await page.goto('http://localhost:13000/services');
 await authenticate('operadora-a','http://localhost:13000/services');
 await page.waitForURL('http://localhost:13000/services');
 await page.getByRole('heading',{name:'Serviços',exact:true}).waitFor();
 evidence.push({check:'OIDC Authorization Code PKCE + password + OTP in Chromium',status:'PASS'});
 const seededService=page.getByRole('link',{name:/Abrir Consulta cadastral fixture/}).first();
 phase='editor do serviço seedado';
 await seededService.waitFor();
 await seededService.click();
 await page.waitForURL('http://localhost:13000/services/consulta-cadastral/1');
 await page.locator('#field-adapter_contract').waitFor();
 evidence.push({check:'Admin service editor exposes declarative REST adapter contract',status:'PASS'});
 await page.getByRole('link',{name:'Voltar à lista',exact:true}).click();
 await page.waitForURL('http://localhost:13000/services');
 phase='resposta JSON inválida da autoridade';
 await page.route('**/api/atlas/admin/v1/services**',route=>route.fulfill({status:200,contentType:'application/json',body:'{not-json'}));
 await page.getByRole('button',{name:'Atualizar',exact:true}).click();
 await page.getByRole('alert').filter({hasText:'Resposta inválida da autoridade'}).waitFor();
 await page.unroute('**/api/atlas/admin/v1/services**');
 evidence.push({check:'Admin rejects invalid JSON response without false success',status:'PASS'});
 await page.getByRole('button',{name:'Atualizar',exact:true}).click();
 await page.getByRole('link',{name:/Abrir Consulta cadastral fixture/}).first().waitFor();
 phase='pesquisa local de referencias';
 await page.getByRole('link',{name:'Ofertas',exact:true}).click();
 await page.waitForURL('http://localhost:13000/offers');
 await page.getByRole('link',{name:'Criar rascunho',exact:true}).click();
 await page.waitForURL('http://localhost:13000/offers/new');
 const applicationSearch=page.getByLabel('Pesquisar Aplicação',{exact:true});
 await applicationSearch.waitFor();
 await page.waitForFunction(()=>document.querySelector('#field-application_id option[value="app-acme@1"]'));
 await applicationSearch.fill('sem-correspondencia');
 await page.waitForFunction(()=>!document.querySelector('#field-application_id option[value="app-acme@1"]'));
 evidence.push({check:'Admin reference editor filters loaded catalog options locally',status:'PASS'});
 await page.getByRole('link',{name:'Voltar à lista',exact:true}).click();
 await page.waitForURL('http://localhost:13000/offers');
 phase='criação e readback do cliente';
 const clientCode=`browser-client-${Date.now()}`;
 await page.getByRole('link',{name:'Clientes',exact:true}).click();
 await page.getByRole('heading',{name:'Clientes',exact:true}).waitFor();
 await page.getByRole('link',{name:'Criar rascunho',exact:true}).click();
 await page.getByLabel('Nome',{exact:true}).fill(`Browser ${clientCode}`);
 await page.getByLabel('Código estável',{exact:true}).fill(clientCode);
 await page.locator('#field-environment').selectOption('local');
 await page.locator('#field-cell_id').fill('r2-cell-a');
 await page.locator('#field-capacity_units').fill('1');
 await page.locator('#field-isolation_class').selectOption('SHARED');
 await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();
 await page.waitForURL(/http:\/\/localhost:13000\/clients\/[^/]+\/1/);
 await page.reload({waitUntil:'networkidle'});
 if(page.url().includes('/realms/')||await page.getByRole('button',{name:'Entrar',exact:true}).count())await authenticate('operadora-a',/http:\/\/localhost:13000\/clients\/[^/]+\/1/);
 await page.waitForURL(/http:\/\/localhost:13000\/clients\/[^/]+\/1/);
 await page.locator(`input[value="Browser ${clientCode}"]`).waitFor();
 evidence.push({check:'Admin resource save, reload and durable readback',status:'PASS',resource:clientCode});
 phase='conflito de edição administrativa';
sqlControl(`UPDATE catalog_resources SET revision=revision+1,updated_at=clock_timestamp() WHERE kind='clients' AND id='${clientCode}' AND version=1`);
 await page.getByLabel('Nome',{exact:true}).fill(`Browser ${clientCode} edição local`);
 await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();
 await page.getByRole('heading',{name:'Outra revisão foi salva',exact:true}).waitFor();
 await page.getByLabel('Sua edição',{exact:true}).waitFor();
 await page.getByLabel('Versão atual',{exact:true}).waitFor();
 evidence.push({check:'Admin edit conflict preserves local input and shows server diff',status:'PASS',resource:clientCode});
 phase='editor de produto e mapeamento dependente';
 const productCode=`browser-product-${Date.now()}`;
 await page.getByRole('link',{name:'Produtos',exact:true}).click();
 await page.waitForURL('http://localhost:13000/products');
 await page.getByRole('link',{name:'Criar rascunho',exact:true}).click();
 await page.getByRole('heading',{name:'Produtos',exact:true}).waitFor();
 await page.getByLabel('Nome',{exact:true}).fill(`Produto ${productCode}`);
 await page.getByLabel('Código estável',{exact:true}).fill(productCode);
 await page.locator('#field-max_parallel').fill('2');
 await page.getByRole('button',{name:'Adicionar passo',exact:true}).click();
 await page.getByRole('button',{name:'Adicionar passo',exact:true}).click();
 const stepNames=page.getByLabel('Nome do passo',{exact:true});
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('select')).some(select=>Array.from(select.options).some(option=>option.value==='protocolo-assincrono@1')));
 await stepNames.nth(0).fill('etapa_a');
 await stepNames.nth(1).fill('etapa_b');
 await page.locator('div.step').nth(0).locator('select').nth(0).selectOption('protocolo-assincrono@1');
 await page.locator('div.step').nth(1).locator('select').nth(0).selectOption('protocolo-assincrono@1');
 await page.getByLabel('Depende dos passos (separados por vírgula)',{exact:true}).nth(1).fill('etapa_a');
 await page.locator('#step-1-input-mapping').fill('{"marker":"etapa_a.marker"}');
 await page.getByRole('button',{name:'Salvar rascunho',exact:true}).click();
 await page.waitForURL(/http:\/\/localhost:13000\/products\/[^/]+\/1/);
 await page.reload({waitUntil:'networkidle'});
 if(await page.getByRole('button',{name:'Entrar',exact:true}).count())await authenticate('operadora-a',/http:\/\/localhost:13000\/products\/[^/]+\/1/);
 if(await page.locator('#step-1-input-mapping').inputValue()!=='{\n  "marker": "etapa_a.marker"\n}')throw new Error('input_mapping do produto não reapareceu no readback');
 evidence.push({check:'Admin product editor persists dependent input mapping',status:'PASS',resource:productCode});
 phase='navegação e relatórios administrativos';
 await page.getByRole('link',{name:'Provedores',exact:true}).click();
 await page.waitForURL('http://localhost:13000/providers');
 await page.getByRole('heading',{name:'Provedores',exact:true}).waitFor();
 evidence.push({check:'URL navigation and real authenticated provider list',status:'PASS'});
 await page.getByRole('link',{name:'SLA bilateral',exact:true}).click();
 await page.waitForURL('http://localhost:13000/sla-reports');
 await page.getByRole('heading',{name:'SLA bilateral',exact:true}).waitFor();
 await page.locator('table').waitFor();
 evidence.push({check:'Admin bilateral SLA report reads persisted protocol snapshots',status:'PASS'});
 phase='redelivery administrativo';
 seededDelivery=randomUUID();
 const seededProtocol=randomUUID();
 const seededEvent=randomUUID();
 sql(`INSERT INTO deliveries(delivery_id,protocol_id,event_id,destination_url,state,next_attempt_at,tenant_id,cell_id,representation,body_sha256) VALUES('${seededDelivery}','${seededProtocol}','${seededEvent}','http://redelivery-fixture.invalid/webhook','EXHAUSTED',clock_timestamp(),'acme','r2-cell-a',decode('7b2266697874757265223a22726564656c6976657279227d','hex'),'browser-redelivery-fixture')`);
 await page.getByRole('link',{name:'Entregas',exact:true}).click();
 await page.waitForURL('http://localhost:13000/deliveries');
 await page.evaluate(id=>{history.pushState({},'',`/deliveries/${id}`);window.dispatchEvent(new PopStateEvent('popstate'))},seededDelivery);
 await page.waitForURL(`http://localhost:13000/deliveries/${seededDelivery}`);
 await page.getByRole('heading',{name:'Detalhe persistido',exact:true}).waitFor();
 await page.getByLabel('Justificativa',{exact:true}).fill('ensaio de redelivery administrativo');
 await page.getByRole('button',{name:'Reentregar mesmos bytes do webhook',exact:true}).click();
 const redeliveryStatus=page.getByRole('status').filter({hasText:'Ação registrada'});
 await redeliveryStatus.waitFor();
 const redeliveryReceipt=await redeliveryStatus.innerText();
 if(!redeliveryReceipt.includes(seededDelivery)||!redeliveryReceipt.includes('RETRY_SCHEDULED'))throw new Error('redelivery sem recibo RETRY_SCHEDULED');
 const auditCount=sql(`SELECT count(*) FROM webhook_audit WHERE tenant_id='acme' AND resource='${seededDelivery}' AND action='REDELIVER_SAME_BYTES' AND length(trim(subject))>0`);
 if(auditCount!=='1')throw new Error(`redelivery sem auditoria durável: ${auditCount}`);
 evidence.push({check:'Admin redelivery changes exhausted delivery and records durable audit',status:'PASS',delivery:seededDelivery});
 phase='reconciliação administrativa';
 const unknownProtocol=sql("SELECT p.protocol_id FROM protocols p JOIN operations o ON o.protocol_id=p.protocol_id AND o.tenant_id=p.tenant_id WHERE p.tenant_id='acme' AND o.state='UNKNOWN' AND o.provider_request_id IS NULL ORDER BY p.accepted_at DESC LIMIT 1");
 if(!unknownProtocol)throw new Error('nenhum protocolo UNKNOWN sem correlação para o ensaio de reconciliação');
 await page.getByRole('link',{name:'Protocolos',exact:true}).click();
 await page.waitForURL('http://localhost:13000/protocols');
 await page.evaluate(id=>{history.pushState({},'',`/protocols/${id}`);window.dispatchEvent(new PopStateEvent('popstate'))},unknownProtocol);
 await page.waitForURL(`http://localhost:13000/protocols/${unknownProtocol}`);
 await page.getByRole('heading',{name:'Detalhe persistido',exact:true}).waitFor();
 await page.getByLabel('Justificativa',{exact:true}).fill('evidência externa ausente');
 await page.getByRole('button',{name:'Solicitar reconciliação',exact:true}).click();
 await page.getByRole('alert').filter({hasText:'provider_request_id ausente'}).waitFor();
 const reconciliationState=sql(`SELECT state FROM protocol_reconciliation_requests WHERE tenant_id='acme' AND protocol_id='${unknownProtocol}' ORDER BY created_at DESC LIMIT 1`);
 if(reconciliationState!=='REJECTED')throw new Error(`reconciliação sem rejeição durável: ${reconciliationState}`);
 const reconciliationAudit=sql(`SELECT count(*) FROM protocol_access_audit WHERE requested_tenant='acme' AND resource='${unknownProtocol}' AND action='RECONCILIATION_REJECTED' AND length(trim(reason))>0`);
 if(Number(reconciliationAudit)<1)throw new Error(`reconciliação sem auditoria durável: ${reconciliationAudit}`);
 evidence.push({check:'Admin reconciliation refuses missing provider correlation with durable rejection',status:'PASS',protocol:unknownProtocol});
 await page.getByRole('link',{name:'Destinos webhook',exact:true}).click();
 await page.waitForURL('http://localhost:13000/destinations');
 await page.getByRole('heading',{name:'Destinos de webhook versionados',exact:true}).waitFor();
 await page.getByRole('heading',{name:'Destinos persistidos',exact:true}).waitFor();
 await page.waitForFunction(()=>!document.querySelector('button[type="submit"]')?.hasAttribute('disabled'));
 await page.getByLabel('Aplicação (vazio = tenant)').fill('app-a');
 await page.getByLabel('URL autorizada').fill('http://webhook-sink:8091/events');
 await page.getByRole('button',{name:'Publicar versão',exact:true}).click();
 const publishStatus=page.locator('.status-ok');
 await publishStatus.waitFor();
 if(!/^Destino .* v1 publicado\.$/.test(await publishStatus.innerText()))throw new Error('publicação de destino sem recibo de sucesso');
 await page.getByRole('link',{name:'Serviços',exact:true}).click();
 await page.waitForURL('http://localhost:13000/services');
 await page.getByRole('link',{name:'Destinos webhook',exact:true}).click();
 await page.waitForURL('http://localhost:13000/destinations');
 await page.getByRole('heading',{name:'Destinos persistidos',exact:true}).waitFor();
 const destinationRow=page.locator('tbody tr').filter({hasText:'app-a'}).first();
 await destinationRow.waitFor();
 if(!await destinationRow.innerText().then(text=>text.includes('webhook-sink:8091/events')))throw new Error('destino publicado não reapareceu na consulta persistida');
 evidence.push({check:'Admin destination publish, reload and durable readback',status:'PASS'});
 evidence.push({check:'Admin versioned webhook destinations reads persisted application snapshot policy',status:'PASS'});
 await page.getByRole('link',{name:'Financeiro',exact:true}).click();
 await page.waitForURL('http://localhost:13000/finance');
 await page.getByRole('heading',{name:'Financeiro e conciliação',exact:true}).waitFor();
 await page.locator('dl.definition-list').waitFor();
 await page.getByRole('link',{name:'Compra e venda',exact:true}).click();
 await page.waitForURL('http://localhost:13000/finance?view=facts');
 await page.locator('dl.definition-list').waitFor();
 await page.getByRole('link',{name:'Journal',exact:true}).click();
 await page.waitForURL('http://localhost:13000/finance?view=journal');
 await page.waitForFunction(()=>document.querySelector('dl.definition-list dd pre')?.textContent?.includes('batch_id'));
 evidence.push({check:'Admin finance accounts, facts and journal read persisted Libra data',status:'PASS'});
 const journalEntries=JSON.parse(await page.locator('dl.definition-list dd pre').first().innerText());
 if(!Array.isArray(journalEntries)||!journalEntries[0]?.batch_id)throw new Error('journal persistido sem batch_id para o ensaio de segregação');
 const adjustmentReason=`browser-segregation-${Date.now()}`;
 await page.getByRole('link',{name:'Ajustes',exact:true}).click();
 await page.waitForURL('http://localhost:13000/finance?view=adjustments');
 await page.getByLabel('Lançamento de origem',{exact:true}).fill(String(journalEntries[0].batch_id));
 await page.getByLabel('Razão do ajuste',{exact:true}).fill(adjustmentReason);
 await page.getByRole('button',{name:'Preparar ajuste',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Ação persistida'}).waitFor();
 const ownAdjustment=page.locator('li').filter({hasText:adjustmentReason});
 await ownAdjustment.waitFor();
 if(await ownAdjustment.getByRole('button',{name:'Aprovar',exact:true}).count())throw new Error('preparador recebeu comando de autoaprovação');
 await ownAdjustment.getByText('Aguardando aprovador distinto',{exact:true}).waitFor();
 evidence.push({check:'Admin finance adjustment enforces distinct approver in the portal',status:'PASS',reason:adjustmentReason});
 await page.getByRole('link',{name:'Fechamentos',exact:true}).click();
 await page.waitForURL('http://localhost:13000/finance?view=periods');
 await page.getByLabel('Início',{exact:true}).fill('2020-01-01');
 await page.getByLabel('Fim (exclusivo)',{exact:true}).fill('2020-01-02');
 await page.getByRole('button',{name:'Verificar e fechar período',exact:true}).click();
 await page.getByRole('alert').filter({hasText:'financial_obligations_open'}).waitFor();
 evidence.push({check:'Admin finance close refuses unresolved obligations with explicit error',status:'PASS'});
 const storage=await page.evaluate(()=>({local:Object.keys(localStorage),session:Object.keys(sessionStorage)}));
 if(storage.local.length||storage.session.includes('atlas.pkce'))throw new Error('Unexpected persisted session material');
 evidence.push({check:'R2-SEG-05-S02 session state has no persistent token and PKCE transaction removed',status:'PASS',storageKeys:storage});
 await page.screenshot({path:'hub/evidence/r2/execution/admin-providers.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 const overflowInfo=await page.evaluate(()=>({
  viewport:innerWidth,
  scrollWidth:document.documentElement.scrollWidth,
  scrollContainers:Array.from(document.querySelectorAll('*')).map(element=>{const rect=element.getBoundingClientRect();const style=getComputedStyle(element);return {element:element.tagName.toLowerCase(),className:typeof element.className==='string'?element.className:'',clientWidth:element.clientWidth,scrollWidth:element.scrollWidth,width:Math.round(rect.width),right:Math.round(rect.right),overflowX:style.overflowX}}).filter(item=>item.scrollWidth>item.clientWidth+1).slice(0,12)
 }));
 const overflow=overflowInfo.scrollWidth>overflowInfo.viewport;
 const dimensions=await page.evaluate(()=>Array.from(document.querySelectorAll('.app-shell,.app-header,.app-nav,.app-main')).map(e=>({element:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right,display:getComputedStyle(e).display,direction:getComputedStyle(e).flexDirection})));
 evidence.push({check:'390px viewport has no page overflow',status:overflow?'FAIL':'PASS',dimensions,overflowInfo});
 if(overflow)process.exitCode=1;
 await page.getByRole('button',{name:'Sair',exact:true}).click();
 await page.waitForURL('http://localhost:13000/services',{timeout:5000});
 const unauthenticatedStatus=await page.request.get('http://localhost:13000/api/atlas/admin/v1/clients?tenant_id=acme').then(response=>response.status());
 if(unauthenticatedStatus!==401)throw new Error(`API administrativa sem sessão retornou HTTP ${unauthenticatedStatus}`);
 evidence.push({check:'R2-SEG-05-S02 logout revokes browser access to administrative API',status:'PASS',httpStatus:unauthenticatedStatus});
 evidence.push({check:'R2-SEG-05-S02 logout navigation',status:'OBSERVED',origin:new URL(page.url()).origin});
 phase='leitor de tenant sem escrita de destinos';
 await page.goto('http://localhost:13000/destinations');
 await authenticate('leitor-a','http://localhost:13000/destinations');
 await page.getByRole('heading',{name:'Destinos de webhook versionados',exact:true}).waitFor();
 await page.getByRole('note').filter({hasText:'não pode publicar novas versões'}).waitFor();
 if(await page.getByRole('button',{name:'Publicar versão',exact:true}).count())throw new Error('tenant_reader recebeu formulário de publicação de destino');
 await page.getByRole('heading',{name:'Destinos persistidos',exact:true}).waitFor();
 evidence.push({check:'Tenant reader sees destinations read-only and no write form',status:'PASS'});
 await page.getByRole('link',{name:'Protocolos',exact:true}).click();
 await page.waitForURL('http://localhost:13000/protocols');
 await page.getByRole('heading',{name:'Protocolos',exact:true}).waitFor();
 const readerProtocol=page.locator('tbody tr a').first();
 if(await readerProtocol.count()){
  await readerProtocol.click();
  await page.getByRole('heading',{name:'Detalhe persistido',exact:true}).waitFor();
  if(await page.getByRole('button',{name:'Solicitar reconciliação',exact:true}).count())throw new Error('tenant_reader recebeu ação de reconciliação');
 }
 evidence.push({check:'Tenant reader consults protocols without reconciliation action',status:'PASS'});
 await page.getByRole('link',{name:'Financeiro',exact:true}).click();
 await page.waitForURL('http://localhost:13000/finance');
 await page.getByRole('link',{name:'Fechamentos',exact:true}).click();
 await page.waitForURL('http://localhost:13000/finance?view=periods');
 await page.getByRole('heading',{name:'Financeiro e conciliação',exact:true}).waitFor();
 if(await page.getByRole('button',{name:'Verificar e fechar período',exact:true}).count())throw new Error('tenant_reader recebeu comando financeiro');
 evidence.push({check:'Tenant reader sees finance queries without mutation commands',status:'PASS'});
 await page.getByRole('button',{name:'Sair',exact:true}).click();
 await page.waitForURL('http://localhost:13000/services',{timeout:5000});
 phase='leitor global cross-tenant';
 await page.goto('http://localhost:13000/protocols');
 await authenticate('auditor-global','http://localhost:13000/protocols');
 await page.getByRole('heading',{name:'Protocolos',exact:true}).waitFor();
 const globalTenant=page.getByLabel('Cliente em consulta',{exact:true});
 await globalTenant.fill('acme');
 const globalReason=page.getByLabel('Finalidade da consulta',{exact:true});
 await globalReason.fill('diagnostico operacional');
 await page.getByRole('button',{name:'Consultar',exact:true}).click();
 const globalRow=page.locator('tbody tr').filter({hasText:'acme'}).first();
 await globalRow.waitFor();
 await globalRow.getByRole('link').first().click();
 await page.getByRole('heading',{name:'Detalhe persistido',exact:true}).waitFor();
 if(await page.getByRole('button',{name:'Solicitar reconciliação',exact:true}).count())throw new Error('leitor global recebeu ação de escrita no portal');
 evidence.push({check:'Global reader consults cross-tenant protocol with audited purpose and no write action',status:'PASS'});
 await page.getByRole('button',{name:'Sair',exact:true}).click();
 await page.waitForTimeout(500);
 console.log(JSON.stringify(evidence,null,2));
} catch(error) {evidence.push({check:'browser flow',status:'FAIL',phase,url:page.url(),error:error.message.split('\n')[0],bodyText:(await page.locator('body').innerText().catch(()=>'' )).slice(0,800),networkDiagnostics});console.log(JSON.stringify(evidence,null,2));process.exitCode=1}
finally {
 if(seededDelivery){try{sql(`DELETE FROM webhook_audit WHERE resource='${seededDelivery}'`);sql(`DELETE FROM deliveries WHERE delivery_id='${seededDelivery}'`)}catch(error){console.error(`cleanup da fixture de redelivery falhou: ${error.message}`)}}
 await writeFile('hub/evidence/r2/execution/browser-smoke.json',JSON.stringify(evidence,null,2)+'\n');await browser.close()
}
